
name: Python package installation

on:
  push:
    branches:
      - main

jobs:
  install_dependencies:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential wget
        sudo apt-get install -y libffi-dev
        sudo apt-get install -y libatlas-base-dev
        sudo apt-get install -y python3-dev
        sudo apt-get install -y libssl-dev
        sudo apt-get install -y libcurl4-openssl-dev

        # دانلود و نصب TA-Lib
        wget http://prdownloads.sourceforge.net/ta-lib/ta-lib-0.4.0-src.tar.gz
        tar -xvzf ta-lib-0.4.0-src.tar.gz
        cd ta-lib
        ./configure
        make
        sudo make install

    - name: Install Python dependencies
      run: |
        pip install --upgrade pip
        pip install TA-Lib
        pip install -r requirements.txt

    - name: Run trading script
      run: |
        # اجرای اسکریپت تریدینگ
        python3 your_trading_script.py

    - name: Post checkout repository
      run: |
        # مرحله پست چک‌اوت
        echo "Post checkout cleanup"

    - name: Send results via email
      run: |
        python3 send_email.py
      env:
        EMAIL_SENDER: ${{ secrets.EMAIL_SENDER }}
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        EMAIL_RECEIVER: ${{ secrets.EMAIL_RECEIVER }}
