name: Run Trading Script

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 * * * *'  # اجرای هر یک ساعت

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential wget tar

      - name: Install TA-Lib from source
        run: |
          wget http://prdownloads.sourceforge.net/ta-lib/ta-lib-0.4.0-src.tar.gz
          tar -xvzf ta-lib-0.4.0-src.tar.gz
          cd ta-lib
          ./configure --prefix=/usr
          make
          sudo make install

      - name: Install Python dependencies
        run: |
          pip install --upgrade pip
          pip install ccxt pandas smtplib ta-lib

      - name: Run Script
        env:
          EMAIL_SENDER: ${{ secrets.EMAIL_SENDER }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          EMAIL_RECEIVER: ${{ secrets.EMAIL_RECEIVER }}
        run: python main.py
