name: Run Trading Script

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 * * * *'

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential autoconf libtool ta-lib

      - name: Add TA-Lib library path
        run: |
          echo "/usr/local/lib" | sudo tee -a /etc/ld.so.conf.d/ta-lib.conf
          sudo ldconfig

      - name: Verify TA-Lib Installation
        run: ls -l /usr/lib/libta_lib.so* || echo "TA-Lib not found!"

      - name: Install Python dependencies manually
        run: |
          python -m pip install --upgrade pip
          pip install ccxt pandas ta-lib

      - name: Run trading script
        run: python main.py
        env:
          EMAIL_SENDER: ${{ secrets.EMAIL_SENDER }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          EMAIL_RECEIVER: ${{ secrets.EMAIL_RECEIVER }}
