name: Run Python Script with Zigzag Calculation

on:
  push:
    branches:
      - main  # یا هر برنچ دیگری که می‌خواهید workflow روی آن اجرا شود
  workflow_dispatch:  # امکان اجرای دستی

jobs:
  run:
    runs-on: ubuntu-latest  # اجرای روی آخرین نسخه اوبونتو

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2  # کلون کردن مخزن

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # یا نسخه‌ای که نیاز دارید

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ccxt pandas pyti smtplib

      - name: Run Python script
        env:
          EMAIL_SENDER: ${{ secrets.EMAIL_SENDER }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          EMAIL_RECEIVER: ${{ secrets.EMAIL_RECEIVER }}
        run: |
          python main.py  # جایگزین با نام اسکریپت شما
